on: push
name: build
jobs:
  go-test:
    name: Go Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: go1.11 linters
      uses: shoukoo/golang-pipeline/go1.11/linter@master
    - name: go1.11 test
      uses: shoukoo/golang-pipeline/go1.11/test@master
    - name: go1.12 test
      uses: shoukoo/golang-pipeline/go1.12/test@master
    - name: go1.13 test
      uses: shoukoo/golang-pipeline/go1.13/test@master
