on: push
name: Build on Push
jobs:
  testing:
    name: Test Go 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Go1.11 test
      uses: ./.github/actions/go1.11
