on: push
name: build
jobs:
  go-test:
    name: Test Go 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: go1.11
      uses: shoukoo/golang-pipeline/go1.11/linter@improvement
