on: push
name: build
jobs:
  go-test:
    name: Test Go 
    runs-on: ubuntu-latest
    steps:
    - name: go1.11 linter
      uses: shoukoo/golang-pipeline/go1.11/linter@improvement
    - name: go1.11 test
      uses: shoukoo/golang-pipeline/go1.11/test@improvement
