on: push
name: build
jobs:
  go-test:
    name: Test Go 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: go1.11 linters
      uses: shoukoo/golang-pipeline/go1.11/linter@improvement
    - name: go1.11 test
      uses: shoukoo/golang-pipeline/go1.11/test@improvement
    - name: go1.12 test
      uses: shoukoo/golang-pipeline/go1.11/test@improvement
    - name: go1.13 test
      uses: shoukoo/golang-pipeline/go1.11/test@improvement
