on: push
name: Build on Push
jobs:
  go-test:
    name: Test Go 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Go1.12 test
      uses: ./.github/actions/go1.12
    - name: Go1.11 test
      uses: ./.github/actions/go1.11
