on: release
name: Build on release
jobs:
  build:
    name: Build Go
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: release
      uses: shoukoo/golang-pipeline/release@master
      if: github.event.action == 'published'
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
